/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LFSR.h"
#include "Length_Counter.h"
#include "Clock_179.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Length_Counter_1.h"
#include "volume_generator.h"
#include "Tri_Divider.h"
#include "Noise_Clk_Div.h"
#include "DAC_Clk.h"
#include "Noise_Out_aliases.h"
#include "Noise_Out.h"
#include "Counter_1.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Noise_Vol_Clk_Div.h"
#include "VDAC8_Noise.h"
#include "Count7_1.h"
#include "Control_Reg_1.h"
#include "MIDI1_UART.h"
#include "USBMIDI_1.h"
#include "USBMIDI_1_audio.h"
#include "USBMIDI_1_cdc.h"
#include "USBMIDI_1_hid.h"
#include "USBMIDI_1_midi.h"
#include "USBMIDI_1_pvt.h"
#include "USBMIDI_1_cydmac.h"
#include "USBMIDI_1_msc.h"
#include "Count7_2.h"
#include "Control_Reg_2.h"
#include "Control_Reg_3.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Control_Reg_4.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Status_Reg_1.h"
#include "rectangle_generator.h"
#include "MIDI1_UART_IntClock.h"
#include "USBMIDI_1_Dm_aliases.h"
#include "USBMIDI_1_Dm.h"
#include "USBMIDI_1_Dp_aliases.h"
#include "USBMIDI_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

